fix: Version: 404 Android: 19 java.lang.NoClassDefFoundError: android/os/PersistableBundle at java.lang.Class.getDeclaredMethods(Native Method) at java.lang.Class.getPublicMethodsRecursive(Class.java:894) at java.lang.Class.getMethods(Class.java:877) at org.mozilla.javascript.JavaMembers.discoverAccessibleMethods(JavaMembers.java:346) at org.mozilla.javascript.JavaMembers.discoverAccessibleMethods(JavaMembers.java:302) at org.mozilla.javascript.JavaMembers.reflect(JavaMembers.java:419) at org.mozilla.javascript.JavaMembers.<init>(JavaMembers.java:43) at org.mozilla.javascript.JavaMembers.lookupClass(JavaMembers.java:807) at org.mozilla.javascript.NativeJavaObject.initMembers(NativeJavaObject.java:54) at org.mozilla.javascript.NativeJavaObject.<init>(NativeJavaObject.java:44) at org.mozilla.javascript.NativeJavaObject.<init>(NativeJavaObject.java:34) at org.mozilla.javascript.WrapFactory.wrapAsJavaObject(WrapFactory.java:115) at org.mozilla.javascript.WrapFactory.wrap(WrapFactory.java:72) at com.stardust.autojs.engine.RhinoJavaScriptEngine$WrapFactory.wrap(RhinoJavaScriptEngine.java:178) at org.mozilla.javascript.Context.javaToJS(Context.java:1838) at com.stardust.autojs.engine.RhinoJavaScriptEngine.put(RhinoJavaScriptEngine.java:64) at com.stardust.autojs.execution.ScriptExecuteActivity.prepare(ScriptExecuteActivity.java:126) at com.stardust.autojs.execution.ScriptExecuteActivity.runScript(ScriptExecuteActivity.java:96) at com.stardust.autojs.execution.ScriptExecuteActivity.onCreate(ScriptExecuteActivity.java:75) at android.app.Activity.performCreate(Activity.java:5397) at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113) at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) at android.app.ActivityThread.access$800(ActivityThread.java:135) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:136) at android.app.ActivityThread.main(ActivityThread.java:5021) at java.lang.reflect.Method.invokeNative(Native Method) at java.lang.reflect.Method.invoke(Method.java:515) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:827) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:643) at dalvik.system.NativeStart.main(Native Method) Caused by: java.lang.ClassNotFoundException: Didn't find class "android.os.PersistableBundle" on path: DexPathList[[zip file "/data/app/org.autojs.autojs-1.apk", zip file "/data/data/org.autojs.autojs/code_cache/secondary-dexes/org.autojs.autojs-1.apk.classes2.zip"],nativeLibraryDirectories=[/data/app-lib/org.autojs.autojs-1, /system/lib, /system/lib/arm, /data/downloads]] at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56) at java.lang.ClassLoader.loadClass(ClassLoader.java:497) at java.lang.ClassLoader.loadClass(ClassLoader.java:457) ... 33 more